[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "moltrans-onmt"
version = "0.1.0"
description = "MolTrans Fork"
authors = ["You"]
packages = [{include = "moltrans_onmt", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.10"